packages/account-hierarchy/main/default/objects/Account/fields/Root_Record_Formula__c.field-meta.xml
<CustomField>
    <fullName>Root_Record_Formula__c</fullName>
    <description>Goes 6 levels up for parent ID</description>
    <formula>IF(NOT(ISBLANK( Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id )),
        Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id ,
        IF(NOT(ISBLANK( Parent.Parent.Parent.Parent.Parent.Parent.Id )),
        Parent.Parent.Parent.Parent.Parent.Parent.Id ,
        IF(NOT(ISBLANK( Parent.Parent.Parent.Parent.Parent.Id )),
        Parent.Parent.Parent.Parent.Parent.Id ,
        IF(NOT(ISBLANK( Parent.Parent.Parent.Parent.Id )), Parent.Parent.Parent.Parent.Id ,
        IF(NOT(ISBLANK( Parent.Parent.Parent.Id )), Parent.Parent.Parent.Id ,
        IF(NOT(ISBLANK( Parent.Parent.Id )), Parent.Parent.Id ,
        IF(NOT(ISBLANK( ParentId )), ParentId ,
        NULL)))))))</formula>
    <label>Root Record Formula</label>
    <type>Text</type>
</CustomField>

packages/account-hierarchy/main/default/objects/Account/fields/Root_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Root_Record_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Record Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Family</relationshipLabel>
    <relationshipName>AccountFamily</relationshipName>
    <type>Lookup</type>
</CustomField>

account-hierarchy/main/default/classes/AccountHierarchyHelper.cls
public with sharing class AccountHierarchyHelper {

    public AccountHierarchyHelper() {
        
    }

    public void syncParentLookupWithFormula(List<Account> accounts){
        for(Account act : accounts){
            if(act.ParentId == null){
                act.Root_Record_Id__c = null;
                continue;
            }
            //in a tree
            if(String.isBlank(act.Root_Record_Id__c) || act.Root_Record_Id__c != act.Root_Record_Formula__c){
                if(String.isBlank(act.Root_Record_Formula__c)){
                    //Something is wrong
                    System.debug('Hierarchy issue with Account: ' + act.Id);
                } else {
                    act.Root_Record_Id__c = act.Root_Record_Formula__c;
                }
            }
        }
    }
}